#!/usr/bin/env sh

source ./bootstrap_lib.sh

function Main__usage {
    printf "
Usage: ${0} [options]

Options:
    --test: Do something

"
}

function Main__parse_args {
    while true; do
        case "$1" in
            --help)
                Main__usage
                exit 1
                ;;
            --)
                shift
                break
                ;;
            *)
                echo "$0: Unrecognized option \"$1\""
                Main__usage
                exit 1
                ;;
        esac
    done
}

function Main__main {
    Main__parse_args "$@"

    Bootstrap__python_available
    echo "$?"
}

Main__main "$@"
