#!/usr/bin/env sh

curdir=`pwd`
source ${curdir}/script/bootstrap_lib.sh

function Main__usage {
    printf "
Usage: ${0} [options]

Options:
    --test: Do something

"
}

function Main__parse_args {
    while true; do
        case "$1" in
            --help)
                Main__usage
                exit 1
                ;;
            --)
                shift
                break
                ;;
            *)
                echo "$0: Unrecognized option \"$1\""
                Main__usage
                exit 1
                ;;
        esac
    done
}

function Main__main {
    # Main__parse_args "$@"

    # Bootstrap__python_available
    # echo "$?"

    # Bootstrap__pythonbrew_available

    # Bootstrap__check_for_progs "python pythonbrew ruby"

    local is_venv=`python -c "import sys; print hasattr(sys, 'real_prefix')"`

    if [[ "${is_venv}" == "False" ]]; then
        echo "Please run: 'pybrew venv use promflask'"
        return 1
    fi

    pip install -r ${curdir}/conf/requirements/develop.txt --no-index -f file://${curdir}/lib/python/
}

Main__main "$@"
